### ISSUE TITLE
Can't build on squeeze with shared libs

### ISSUE THREAD

**Issue by tomchipchase** [aw/nodejs-debian#4]
I'm trying to get this to work on squeeze (6.0), and I get errors during the build due to trying to use the shared libraries for openssl and libc-ares. It seems that node needs a newer version than is available on squeeze.

When I removed the --shared-cares and --shared-openssl from debian/rules, I was able to build it.

**Comment by aw** [comment]
Yeah the shared `cares` with debian 7 is also causing issues with newer nodejs. I removed it from the build script.
