### ISSUE TITLE
Support to package v0.12?

### ISSUE THREAD

**Issue by OhJeez** [aw/nodejs-debian#6]
Can we have support for v0.12? (Maybe on separate branch?)

**Comment by aw** [comment]
Hi, sorry I missed this issue. Yes I will add support for v0.12 shortly.
Thanks!

**Comment by aw** [comment]
@OhJeez v0.12 support added. I'm testing now, then I'll add `v0.12.1` and `v0.12.2`.

**Comment by OhJeez** [comment]
Thanks!
