### ISSUE TITLE
package for armhf

### ISSUE THREAD

**Issue by fabriciolelis** [aw/nodejs-debian#8]
Is possible create a deb package for armhf?

**Comment by aw** [comment]
The build script and debian `control` file don't require a specific CPU architecture: https://github.com/aw/nodejs-debian/blob/master/debian/control#L9

Technically it **should** work, but I don't have access to that CPU so I can't confirm.

You can try it out and let me know if you have issues.

**Comment by fabriciolelis** [comment]
I've found a problem
In file included from ../deps/openssl/asm/arm-elf-gas/aes/aes-armv4.S:1:0:
../deps/openssl/openssl/crypto/arm_arch.h:35:5: error: #error "unsupported ARM architecture"
 #   error "unsupported ARM architecture"
     ^
make[2]: *** [/home/fabricio/nodejs-debian/bin/nodejs-0.10.36/out/Release/obj.target/openssl/deps/openssl/asm/arm-elf-gas/aes/aes-armv4.o] Error 1
make[2]: Leaving directory `/home/fabricio/nodejs-debian/bin/nodejs-0.10.36/out'
make[1]: *** [node] Error 2
make[1]: Leaving directory `/home/fabricio/nodejs-debian/bin/nodejs-0.10.36'
dh_auto_build: make -j1 returned exit code 2
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc -j4 failed

Can you help me?

**Comment by aw** [comment]
Hi,

I'm not too familiar with that, but I've found these two pages which might help:

* http://unix.stackexchange.com/questions/77191/backporting-openssl-1-0-1e-to-debian-lenny-armv4l
* http://www.armhf.com/node-js-for-the-beaglebone-black/

In both cases, you would need to edit `line 9` in this file: https://github.com/aw/nodejs-debian/blob/master/debian/rules#L9 then re-run `bin/make-nodejs-deb.sh 0.10.36`

**Comment by fabriciolelis** [comment]
Hi,
I did this changes but the error persists.

**Comment by aw** [comment]
Sorry, this is a **nodejs** build issue, it has nothing to do with my build script.

Can you try installing/compiling nodejs _manually_ using the instructions here: http://nodejs.org/

Once you figure that out and get it compiled, let me know the exact steps/commands you used, and I can try to integrate them into this build script.

Thanks.
